services:
  - type: web
    name: weather-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: API_KEY
        value: 7d1d9790927298a60291acc7abd0e847
